spring:
  datasource:
    url: jdbc:h2:mem:alurachallenge3
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size=: 10MB

  mail:

    host: smtp.gmail.com
    port: 587
    username: **********@gmail.com
    password: ************
#    username: ${SMTP_USERNAME}
#    password: ${SMTP_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true